### ISSUE TITLE
Rocket Launcher and Heatseeker (others untested)

### ISSUE THREAD

**Issue by Crayder** [oscar-broman/samp-weapon-config#9] opened 2015-02-17 01:29 UTC
When hitting somebody with a missile, they can take a missile straight to the face and only lose ~5 to 7 health. Didn't realize until some random guy came in my server and hit me it the face with a missile.

**Comment by oscar-broman** [comment] 2015-02-17 07:00
Did you change anything in `OnPlayerDamage`? Either way, I'll test this.

**Comment by Crayder** [comment] 2015-02-17 13:49
do you wanna just come in my server so i can show the things to you ?

**Comment by oscar-broman** [comment] 2015-02-17 15:18
What's the IP and when are you usually online?

**Comment by Crayder** [comment] 2015-02-17 21:11
I'm home now. I'll be online:

HostName: Test Server [0.3.7]
Address:  68.45.78.40:7777
Password: Crayder

**Comment by oscar-broman** [comment] 2015-03-21 22:10
Can't reproduce. Closing for now.

**Closed by oscar-broman** 2015-03-21 22:10 UTC
Labels: bug, needs-testing
