### ISSUE TITLE
MaxWeaponShootRate

### ISSUE THREAD

**Issue by elvianod982** [oscar-broman/samp-weapon-config#117] opened 2019-12-23 16:16 UTC
I currently use an anti-cheat system on my server which will ban players who use rapidfire. The checking only applies to the Desert Eagle and Sniper Rifle (intentional). 

I figured that instead of doing this, I would look into making weapon-config simply reject the shots. 

I've been playing around with this concept, however have run into a roadblock. I'm opening it as an Issue here on Github just to establish if this is desired, or a bug:

I've changed https://github.com/oscar-broman/samp-weapon-config/blob/master/weapon-config.inc#L627 from 900ms to 5000ms. I know that's a very high value, this is just for testing.

Recording: https://streamable.com/vv2fk

Notice how to start with, the damage is being taken normally, and then towards the end, shots are being rejected.

From my understanding, only one shot per 5 seconds should have registered. Additionally, even after 5 seconds had passed towards the end of the recording, shots were still being rejected. 

By all means, feel free to close this issue if I'm simply misunderstanding the feature, it's probably just me being silly and not understanding how it should work.

**SA:MP Server Version:** 0.3.7-R2
**weapon-config Version:** Up-to-date with [this](https://github.com/oscar-broman/samp-weapon-config/commit/82802369feaaf708f710f32a5f48d689336a2649#diff-bb9c2a9539291b896d938b65a38c33e9) commit
**SKY Version:** 2.1.1
**Operating System:** CentOS 8

**Comment by ADRFranklin** [comment] 2019-12-23 16:26
You do realize you didn't need to modify the script itself? You could of just used
```
SetWeaponShootRate(34, 9000);
```

These where made so that you never had to modify the script.

As for your question which rejected code is given for it? `SHOOTING_RATE_TOO_FAST` or `HIT_RATE_TOO_FAST` ?

**Comment by elvianod982** [comment] 2019-12-25 17:47
Noted, thanks for the heads up.

I've now set `SetWeaponShootRate(24, 15000);` and tested, and see "Hit rate too fast" and "Shooting rate too fast"

Recording: https://streamable.com/m80s0

It would appear that SetWeaponShootRate isn't applying for armour (intentional?) and does eventually start to kick in, but not soon enough. 

In my head, I would expect my second shot to be rejected given that it happened sooner than 15000ms.

**Comment by ADRFranklin** [comment] 2019-12-28 21:29
Could you provide a minimal reproducible example of your code, that shows the issue and can be used to fix?

**Comment by elvianod982** [comment] 2020-01-05 17:28
I've just spun a completely fresh gamemode with grandlarc, and a stock install of the latest version of sky and weapon config, in order to rule out something in my gamemode specifically causing this:

https://streamable.com/yjmto

As you can see, the results are the same. I'm using `SetWeaponShootRate(24, 15000);`

I'd expect that the second shot I fired would be rejected since it happened far quicker than 15 seconds, but instead, the shots only started getting rejected when the player was on half health.

**Comment by elvianod982** [comment] 2020-01-28 21:28
Is there any news for this case?

**Comment by ADRFranklin** [comment] 2020-01-29 04:53
You have yet to provide a minimal reproducible example, I was not able to create this issue myself, and that maybe because of how you have used it, with other weapon-config values.

I will need code from you that shows the issue.

**Comment by ADRFranklin** [comment] 2020-02-03 12:20
Is this still a problem? and if it is, can you provide a minimal reproducible example of the code that causes the issue, so I can investigate it else I have to close this issue.

**Comment by elvianod982** [comment] 2020-02-03 13:07
It is still a problem, but I don't really know what code you are looking for. I literally tried with a blank gamemode (grandlarc) and stock weapon-config/sky. The only change I made was:

SetWeaponShootRate(24, 15000);

And then I fired at a rate faster than 15 seconds with weapon 24, and the shots were not being rejected like they should have been.

**Comment by ADRFranklin** [comment] 2020-02-07 22:51
You actually have it backwards, the ShootRate is actually the gap between each bullet. What you have done is you have told weapon-config, that if the shooting rate is below 15 seconds apart from each other, then it is allowed.

So your code is wrong, and it will never get triggered.

**Closed** 2020-03-12 13:17 UTC
