### ISSUE TITLE
OnPlayer(Prepare)Death crash

### ISSUE THREAD

**Issue by Hoxxy** [oscar-broman/samp-weapon-config#131] opened 2020-03-27 10:53 UTC
Server is crashing when it tries to call OnPlayerPrepareDeath.
fix-hooks branch

> [27/03/2020, 11:49:01] [debug] Server crashed while executing NLRPGv3.amx
[27/03/2020, 11:49:01] [debug] AMX backtrace:
[27/03/2020, 11:49:01] [debug] # 0 native CallLocalFunction () in sampsvr-port_3515
[27/03/2020, 11:49:01] [debug] # 1 0001a6c0 in OnPlayerDeath (playerid=15, killerid=0, reason=51) at C:\Users\Nikola\Documents\GitHub\NLv3\pawno\include\weapon-config.inc:2645
[27/03/2020, 11:49:01] [debug] # 2 0004bc9c in public OnPlayerDeath (15, 65535, 255) at C:\Users\Nikola\Documents\GitHub\NLv3\pawno\include\YSI_Data\y_foreach\..\..\YSI_Coding\y_hooks\..\y_cgen\y_cgen.inc:127
[27/03/2020, 11:49:01] [debug] Native backtrace:
[27/03/2020, 11:49:01] [debug] # 0 f7af78b6 in _Z13GetStackTraceRSt6vectorI10StackFrameSaIS0_EEPv () in plugins/crashdetect.so
[27/03/2020, 11:49:01] [debug] # 1 f7aef120 in _ZN18CrashDetectHandler20PrintNativeBacktraceERSoRKN2os7ContextE () in plugins/crashdetect.so
[27/03/2020, 11:49:01] [debug] # 2 f7aef886 in _ZN18CrashDetectHandler20PrintNativeBacktraceERKN2os7ContextE () in plugins/crashdetect.so
[27/03/2020, 11:49:01] [debug] # 3 f7aeff96 in _ZN18CrashDetectHandler7OnCrashERKN2os7ContextE () in plugins/crashdetect.so
[27/03/2020, 11:49:01] [debug] # 4 f7af6f82 in ?? () in plugins/crashdetect.so
[27/03/2020, 11:49:01] [debug] # 5 f7edfbf0 in __kernel_rt_sigreturn () in linux-gate.so.1
[27/03/2020, 11:49:01] [debug] # 6 080dfdcc in ?? () in ./sampsvr-port_3515
[27/03/2020, 11:49:01] [debug] # 7 080950e4 in ?? () in ./sampsvr-port_3515
[27/03/2020, 11:49:01] [debug] # 8 f7af0b9b in _ZN18CrashDetectHandler15ProcessCallbackEiPiS0_ () in plugins/crashdetect.so
[27/03/2020, 11:49:01] [debug] # 9 f7af4fc2 in ?? () in plugins/crashdetect.so
[27/03/2020, 11:49:01] [debug] # 10 f7af9bc7 in amx_Exec () in plugins/crashdetect.so
[27/03/2020, 11:49:01] [debug] Registers:
[27/03/2020, 11:49:01] [debug] EAX: 00000000 EBX: 00000000 ECX: 0849bac0 EDX: f3428008
[27/03/2020, 11:49:01] [debug] ESI: f56d38fc EDI: 0849bac0 EBP: ff97abf8 ESP: ff97a720
[27/03/2020, 11:49:01] [debug] EIP: 080dfdcc EFLAGS: 00010246
[27/03/2020, 11:49:01] [debug] Stack:
[27/03/2020, 11:49:01] [debug] ESP+00000000: f56d3924 ff97a7c0 ff97a7c4 00000006
[27/03/2020, 11:49:01] [debug] ESP+00000020: 69737369 ff970069 ff97a7d4 00000015
[27/03/2020, 11:49:01] [debug] ESP+00000040: 6c506e4f 72657961 70657250 44657261
[27/03/2020, 11:49:01] [debug] ESP+00000060: 081ee3ec ff97a820 00000001 00000009
[27/03/2020, 11:49:01] [debug] ESP+00000080: ff97a820 00000001 ff97a958 08071a91
[27/03/2020, 11:49:01] [debug] ESP+000000a0: 00000000 f56d3924 081ee490 000000e4
[27/03/2020, 11:49:01] [debug] ESP+000000c0: 00000000 00000000 00000000 00000000
[27/03/2020, 11:49:01] [debug] ESP+000000e0: 00000000 00000000 00000000 00000000
[27/03/2020, 11:49:01] [debug] ESP+00000100: 00000020 00000800 00000000 ff97a831
[27/03/2020, 11:49:01] [debug] ESP+00000120: f7b95b67 ff97aec4 081d89e8 f7eeebb4
[27/03/2020, 11:49:01] [debug] ESP+00000140: 081eebd5 00000005 00000038 00000001
[27/03/2020, 11:49:01] [debug] ESP+00000160: 00000000 00000014 00000020 081d42a4
[27/03/2020, 11:49:01] [debug] ESP+00000180: 00000000 ff97aaa1 ff97a8e8 00000000
[27/03/2020, 11:49:01] [debug] ESP+000001a0: 081ee3ec 0815220c ff97aa51 00000028
[27/03/2020, 11:49:01] [debug] ESP+000001c0: 00000000 ff97aa81 ff97a928 0807c193
[27/03/2020, 11:49:01] [debug] ESP+000001e0: 00000001 00000009 00000002 f7b93afc
[27/03/2020, 11:49:01] [debug] ESP+00000200: 081ee3ec 0815ab32 ff97aab1 00000010
[27/03/2020, 11:49:01] [debug] ESP+00000220: 00000003 0000270f 0000001f 00000000
[27/03/2020, 11:49:01] [debug] ESP+00000240: 081ee3ec 0815cdc6 ff97aae1 00000000
[27/03/2020, 11:49:01] [debug] ESP+00000260: f7cce490 00000000 00000000 ffffffff
[27/03/2020, 11:49:01] [debug] ESP+00000280: 081ee3e8 0815cdc6 ff97aae1 00000000
[27/03/2020, 11:49:01] [debug] ESP+000002a0: 0000e490 00000000 00000000 ffffffff
[27/03/2020, 11:49:01] [debug] ESP+000002c0: 0000001f 02002710 081ee3ec 0000000f
[27/03/2020, 11:49:01] [debug] ESP+000002e0: 081ee3ec 0815cdc6 ff97aad0 00000001
[27/03/2020, 11:49:01] [debug] ESP+00000300: 00000000 00000000 ffffffff ffffffff
[27/03/2020, 11:49:01] [debug] ESP+00000320: 081ee3e8 0815cdc6 ff97aad0 00000001
[27/03/2020, 11:49:01] [debug] ESP+00000340: 00000000 00000000 00000087 f651771c
[27/03/2020, 11:49:01] [debug] ESP+00000360: 4733e36d 0005e490 000003e8 00000000
[27/03/2020, 11:49:01] [debug] ESP+00000380: ff97aad0 0849bac0 ff97abf8 080dca41
[27/03/2020, 11:49:01] [debug] ESP+000003a0: 00000002 f65fd000 ff97ab48 f6518153
[27/03/2020, 11:49:01] [debug] ESP+000003c0: ff97ab01 ff97ab18 ff97ab20 f7cc9069
[27/03/2020, 11:49:01] [debug] ESP+000003e0: 081e1e80 ff97ab38 ff97ab78 f643c5db
[27/03/2020, 11:49:01] [debug] Loaded modules:
[27/03/2020, 11:49:01] [debug] 00000000 - 00187f43 sampsvr-port_3515
[27/03/2020, 11:49:01] [debug] f7edf000 - f7edfd82 linux-gate.so.1
[27/03/2020, 11:49:01] [debug] f7ecc000 - f7ece81b /lib/i386-linux-gnu/i686/cmov/libdl.so.2
[27/03/2020, 11:49:01] [debug] f7eb0000 - f7ecad2b /lib/i386-linux-gnu/i686/cmov/libpthread.so.0
[27/03/2020, 11:49:01] [debug] f7d30000 - f7eb95c0 /home/samp/clients/servfiles/libraries/minimal/libstdc++.so.6
[27/03/2020, 11:49:01] [debug] f7cea000 - f7d2eb43 /lib/i386-linux-gnu/i686/cmov/libm.so.6
[27/03/2020, 11:49:01] [debug] f7ccd000 - f7ce93c4 /lib/i386-linux-gnu/libgcc_s.so.1
[27/03/2020, 11:49:01] [debug] f7b20000 - f7cd522f /lib/i386-linux-gnu/i686/cmov/libc.so.6
[27/03/2020, 11:49:01] [debug] f7ee0000 - f7f00d6c /lib/ld-linux.so.2
[27/03/2020, 11:49:01] [debug] f7ad8000 - f7b1c3ac plugins/crashdetect.so
[27/03/2020, 11:49:01] [debug] f7747000 - f7adceb2 plugins/mysql.so
[27/03/2020, 11:49:01] [debug] f7724000 - f7745108 /home/samp/clients/port_3515/plugins/../log-core.so
[27/03/2020, 11:49:01] [debug] f7712000 - f771909f /lib/i386-linux-gnu/i686/cmov/librt.so.1
[27/03/2020, 11:49:01] [debug] f6703000 - f670e3ef /lib/i386-linux-gnu/i686/cmov/libnss_files.so.2
[27/03/2020, 11:49:01] [debug] f64b4000 - f66089dc plugins/timerfix.so
[27/03/2020, 11:49:01] [debug] f64a3000 - f64b29b4 plugins/sscanf.so
[27/03/2020, 11:49:01] [debug] f63dd000 - f64a2740 plugins/streamer.so
[27/03/2020, 11:49:01] [debug] f6378000 - f63dce6e plugins/regex.so
[27/03/2020, 11:49:01] [debug] f6293000 - f637ab50 plugins/pawncmd.so
[27/03/2020, 11:49:01] [debug] f60f3000 - f629a168 plugins/SKY.so

**Comment by ADRFranklin** [comment] 2020-03-30 13:47
I will look into this

**Comment by ADRFranklin** [comment] 2020-03-30 19:05
I was not able to reproduce this, can you enable debugging
```
#define WC_DEBUG true
```

and then try again

**Comment by ADRFranklin** [comment] 2020-04-05 04:23
@Hoxxy Can you give me an update with that you have tried please? Else I am going to have to close this issue as you haven't responded.

**Closed** 2020-05-30 20:10 UTC
