### ISSUE TITLE
FCNPC Problem `OnPlayerDeath`

### ISSUE THREAD

**Issue by zile42O** [oscar-broman/samp-weapon-config#115] opened 2019-12-23 02:11 UTC
When i killed a NPC, the crashdetect detect this:
```
[02:39:56] [debug] Run time error 4: "Array index out of bounds"
[02:39:56] [debug]  Attempted to read/write array element at index 65535 in array of size 2001
[02:39:56] [debug] AMX backtrace:
[02:39:56] [debug] #0 0000600c in public OnPlayerDeath (playerid=97, killerid=65535, reason=51) at E:\SAMP dev\compiler\include\weapon-config.inc:2494
```
But if i put in gamemode pwn 
in callback OnPlayerDeath this >` if (IsPlayerNPC(playerid)) return false; ` that not be fixed, so
if i put in include weapon-config.inc `if(IsPlayerNPC(playerid)) return false;` in callback OnPlayerDeath  this will be fixed.

**Comment by ADRFranklin** [comment] 2019-12-23 03:34
Your error line, doesn't match up with the current version of weapon-config. Please update your script and than try it again. If it continues please post back here with the new results.

**Comment by zile42O** [comment] 2019-12-23 04:35
You are wrong, this is the last version, but i posted wrong line, you can check and test to see it

**Comment by zile42O** [comment] 2019-12-23 04:35
Check do you have in Onplayerdeath, block for npc?

**Comment by zile42O** [comment] 2019-12-23 04:38
The line is 2564

**Comment by ADRFranklin** [comment] 2019-12-23 14:06
Well I wasn't wrong, since you posted the wrong line. However can you post the code you have for OnPlayerDeath at pastebin or a similar site.

I need to be able to verify this isn't a problem with the way you are using it.

**Comment by zile42O** [comment] 2019-12-23 14:21
What code you need, from crashedetect or from my script? 
I tested that on bare script just included weapon config, and fcnpc, created and spawned npc then i was killed him and crash output in console, i used last weapon config, and sky, but when i remove weapon config from bare script then works all okay, no crashes, so i think the weapon-config.inc need to add in OnPlayerDeath, when set INVALID_PLAYER_ID on line 2564 which i get from crashdetect, the simple fix will be to check if is playerid npc to false callback or ignore code with if(! IsPlayerNPC(playerid)) { callback code..} 
If you want to be sure can you contact me, to see together this issue

**Comment by ADRFranklin** [comment] 2019-12-23 14:26
Well I made it clear what I wanted, but if you can make a bare minimal reproducible script that I can use to test this issue, then please do that.

**Comment by zile42O** [comment] 2019-12-23 14:30
Ofc

**Comment by zile42O** [comment] 2019-12-23 15:02
Screens:
http://prntscr.com/qer9q9
CrashDetect:
```
[15:59:36] [connection] 127.0.0.1:54176 requests connection cookie.
[15:59:37] [connection] incoming connection: 127.0.0.1:54176 id: 0
[15:59:37] [join] zile42O has joined the server (0:127.0.0.1)
[15:59:44] [npc:join] TestNPC has joined the server (49:127.0.0.1)
[15:59:48] [debug] Run time error 4: "Array index out of bounds"
[15:59:48] [debug]  Attempted to read/write array element at index 65535 in array of size 2001
[15:59:48] [debug] AMX backtrace:
[15:59:48] [debug] #0 00006120 in public OnPlayerDeath (playerid=49, killerid=65535, reason=51) at C:\Users\ZILE\Desktop\samp test 037 server\pawno\include\weapon-config.inc:2563
```
Test Script:
https://pastebin.com/XdFbyWAK

**Comment by zile42O** [comment] 2019-12-23 15:04
FCNPC and WC is latest version, and one more thing about WC, why u remove a const from functions?
In new compiler i get this > http://prntscr.com/qercal
But nvm, i fixed that for me.

**Comment by ADRFranklin** [comment] 2019-12-23 15:53
This has been fixed in the latest changes, this also had nothing to do with NPC's. It was an incorrect vehicle check that caused an OOB error.

**Closed by ADRFranklin** 2019-12-23 15:53 UTC
