### ISSUE TITLE
Unreturned death, from InflictDamage

### ISSUE THREAD

**Issue by Crayder** [oscar-broman/samp-weapon-config#14] opened 2015-02-18 03:51 UTC
I think PlayerDeath was never called from InflictDamage. Here is the debug:

![image](https://cloud.githubusercontent.com/assets/9919010/6242152/6287930c-b6f7-11e4-8d13-067d6f639dc1.png)

So all the stuff in PlayerDeath that was needed was never called.

I'm not sure if it's needed, just reporting in case it is...

**Comment by oscar-broman** [comment] 2015-02-18 06:37
What happened? Did you respawn?

**Comment by oscar-broman** [comment] 2015-02-18 06:40
Do you do anything in `OnPlayerDamageDone` in your code, in which case please show it here.

**Comment by Crayder** [comment] 2015-02-18 07:48
Nope, nothing there. OnPlayerPrepareDeath and OnPlayerDeathFinished are both called fine though.

**Comment by oscar-broman** [comment] 2015-02-18 11:02
The only place `OnPlayerPrepareDeath` is called is within `PlayerDeath`.

**Comment by Crayder** [comment] 2015-02-18 13:12
Yes, but I had debug messages at the times for my multi color stuff. They didn't print and they were not in any inner body.

**Comment by oscar-broman** [comment] 2015-03-08 18:56
I will close this since it can't be reproduced/lack of proof, but feel free to open if it happens again and you have more details.

**Closed by oscar-broman** 2015-03-08 18:56 UTC
